# Generated by Django 5.1.7 on 2025-04-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
