# Generated by Django 5.1.7 on 2025-06-02 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagerie", "0002_message_iv_message_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupe_discussion",
                        to="messagerie.conversation",
                    ),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        related_name="groupes_discussion", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("key", models.TextField(blank=True, null=True)),
                ("iv", models.TextField(blank=True, null=True)),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_groupe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messagerie.groupediscussion",
                    ),
                ),
            ],
            options={
                "ordering": ["date_envoi"],
            },
        ),
    ]
