# Generated by Django 5.1.7 on 2025-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagerie", "0003_groupediscussion_messagegroupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="fichiers_messages/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_vocal",
            field=models.FileField(blank=True, null=True, upload_to="messages_vocaux/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="contenu",
            field=models.TextField(blank=True, null=True),
        ),
    ]
