# Generated by Django 5.1.7 on 2025-06-03 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagerie", "0004_message_fichier_message_message_vocal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="key",
            new_name="chiffred_data_base64",
        ),
        migrations.AddField(
            model_name="message",
            name="cle_chiffrement",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="supprime_par_expediteur",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="groupediscussion",
            name="membres",
            field=models.ManyToManyField(
                related_name="groupes_auxquels_appartient", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupediscussion",
            name="nom",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="MessageGroupe",
        ),
    ]
